version: '3'
services:
  photowings:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: photowings
    environment:
      DB_HOST: mongodb
      NODE_ENV: production
      PORT: 80
      TZ: America/Chicago
    ports:
      - 3000:80
      - 10000:10000
    depends_on:
      - mongodb
    volumes:
      - ./src:/usr/src/app/src
      - ./static:/usr/src/app/static
      - /mnt/storage/photos:/photos
  mongodb:
    image: mongo:latest
    container_name: photowings_mongo
    command: --logpath /dev/null
    user: mongodb
    volumes:
      - ./db:/data/db
